// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package example

type Action = byte
const (
	ActionNONE Action = 0
	ActionRez Action = 1
	ActionCollision Action = 2
)

var EnumNamesAction = map[Action]string{
	ActionNONE:"NONE",
	ActionRez:"Rez",
	ActionCollision:"Collision",
}

