// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package example

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Collision struct {
	_tab flatbuffers.Table
}

func GetRootAsCollision(buf []byte, offset flatbuffers.UOffsetT) *Collision {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Collision{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Collision) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Collision) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Collision) MoveStates(obj *MoveState, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 48
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *Collision) MoveStatesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func CollisionStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func CollisionAddMoveStates(builder *flatbuffers.Builder, moveStates flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(moveStates), 0)
}
func CollisionStartMoveStatesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(48, numElems, 8)
}
func CollisionEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
