// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package example

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Gps struct {
	_tab flatbuffers.Struct
}

func (rcv *Gps) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Gps) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *Gps) Latitude() float64 {
	return rcv._tab.GetFloat64(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *Gps) MutateLatitude(n float64) bool {
	return rcv._tab.MutateFloat64(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *Gps) Longitude() float64 {
	return rcv._tab.GetFloat64(rcv._tab.Pos + flatbuffers.UOffsetT(8))
}
func (rcv *Gps) MutateLongitude(n float64) bool {
	return rcv._tab.MutateFloat64(rcv._tab.Pos+flatbuffers.UOffsetT(8), n)
}

func CreateGps(builder *flatbuffers.Builder, latitude float64, longitude float64) flatbuffers.UOffsetT {
	builder.Prep(8, 16)
	builder.PrependFloat64(longitude)
	builder.PrependFloat64(latitude)
	return builder.Offset()
}
