// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package example

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Rez struct {
	_tab flatbuffers.Table
}

func GetRootAsRez(buf []byte, offset flatbuffers.UOffsetT) *Rez {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Rez{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Rez) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Rez) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Rez) Dummy() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *Rez) MutateDummy(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func RezStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func RezAddDummy(builder *flatbuffers.Builder, dummy bool) {
	builder.PrependBoolSlot(0, dummy, false)
}
func RezEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
