// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package vfs_schema

import "strconv"

type Index byte

const (
	IndexNONE              Index = 0
	IndexIndexNum          Index = 1
	IndexIndexString       Index = 2
	IndexFile              Index = 3
	IndexInvertedMapNum    Index = 4
	IndexInvertedMapString Index = 5
	IndexNumList           Index = 6
)

var EnumNamesIndex = map[Index]string{
	IndexNONE:              "NONE",
	IndexIndexNum:          "IndexNum",
	IndexIndexString:       "IndexString",
	IndexFile:              "File",
	IndexInvertedMapNum:    "InvertedMapNum",
	IndexInvertedMapString: "InvertedMapString",
	IndexNumList:           "NumList",
}

var EnumValuesIndex = map[string]Index{
	"NONE":              IndexNONE,
	"IndexNum":          IndexIndexNum,
	"IndexString":       IndexIndexString,
	"File":              IndexFile,
	"InvertedMapNum":    IndexInvertedMapNum,
	"InvertedMapString": IndexInvertedMapString,
	"NumList":           IndexNumList,
}

func (v Index) String() string {
	if s, ok := EnumNamesIndex[v]; ok {
		return s
	}
	return "Index(" + strconv.FormatInt(int64(v), 10) + ")"
}
