// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package query

import "github.com/kazu/fbshelper/query/base"

/*
must call 1 times per Table / struct ( Files ) ;
*/

type Files struct {
	*base.CommonNode
}

func NewFiles() *Files {
	return &Files{CommonNode: &base.CommonNode{}}
}

var Files_IdxToType map[int]int = map[int]int{}
var Files_IdxToTypeGroup map[int]int = map[int]int{}
var Files_IdxToName map[int]string = map[int]string{}
var Files_NameToIdx map[string]int = map[string]int{}

var DUMMP_FilesFalse bool = base.SetNameIsStrunct("Files", base.ToBool("False"))

func SetFilesFields(nName, fName, fType string, fNum int) bool {
	enumFtype, ok := base.NameToType[fType]
	if ok {
		FilesSetIdxToType(fNum, enumFtype)
	}
	//FIXME: basic type only store?

	FilesSetIdxToName(fNum, fType)

	grp := FilesGetTypeGroup(fType)
	FilesSetTypeGroup(fNum, grp)

	Files_IdxToName[fNum] = fType

	Files_NameToIdx[fName] = fNum
	base.SetNameToIdx("Files", Files_NameToIdx)

	return true

}
func FilesSetIdxToName(i int, s string) {
	Files_IdxToName[i] = s

	base.SetIdxToName("Files", Files_IdxToName)
}

func FilesSetIdxToType(k, v int) bool {
	Files_IdxToType[k] = v
	base.SetIdxToType("Files", Files_IdxToType)
	return true
}

func FilesSetTypeGroup(k, v int) bool {
	Files_IdxToTypeGroup[k] = v
	base.SetdxToTypeGroup("Files", Files_IdxToTypeGroup)
	return true
}

func FilesGetTypeGroup(s string) (result int) {
	return base.GetTypeGroup(s)
}

func (node Files) commonNode() *base.CommonNode {
	if node.CommonNode == nil {
		base.Log(base.LOG_WARN, func() base.LogArgs {
			return base.F("CommonNode not found Files")
		})
	} else if len(node.CommonNode.Name) == 0 || len(node.CommonNode.IdxToType) == 0 {
		node.CommonNode.Name = "Files"
		node.CommonNode.IdxToType = Files_IdxToType
		node.CommonNode.IdxToTypeGroup = Files_IdxToTypeGroup
	}
	return node.CommonNode
}
func (node Files) SearchInfo(pos int, fn base.RecFn, condFn base.CondFn) {

	node.commonNode().SearchInfo(pos, fn, condFn)

}

func (node Files) Info() (info base.Info) {

	return node.commonNode().Info()

}

func (node Files) IsLeafAt(j int) bool {

	return node.commonNode().IsLeafAt(j)

}

func (node Files) CountOfField() int {
	return len(Files_IdxToType)
}

func (node Files) ValueInfo(i int) base.ValueInfo {
	return node.commonNode().ValueInfo(i)
}

func (node Files) FieldAt(idx int) *base.CommonNode {
	return node.commonNode().FieldAt(idx)
}
