// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package query

import "github.com/kazu/fbshelper/query/base"

/*
must call per Field
go run github . com / cheekybits / genny gen "File=Root Id=Version Uint64=int64 CommonNode=base.CommonNode 0=0 False=false" ;
go run github . com / cheekybits / genny gen "File=Root Id=Index   Uint64=Index CommonNode=Index        0=1 False=false" ;
*/

// import (
// 	"github.com/cheekybits/genny/generic"
// 	b "github.com/kazu/fbshelper/query/base"
// )

var (
	File_Id_0 int = base.AtoiNoErr(Atoi("0"))
	File_Id   int = File_Id_0
)

// (field inedx, field type) -> File_IdxToType
var DUMMY_File_Id bool = SetFileFields("File", "Id", "Uint64", File_Id_0)

// FileSetNodeToIdx(File_Id, base.NameToTypeEnum("Uint64")) &&
// FileSetIdxToName("Uint64", File_Id)

func (node File) Id() (result *CommonNode) {
	result = NewCommonNode()
	common := node.FieldAt(File_Id_0)

	result.Name = common.Name
	result.NodeList = common.NodeList
	result.IdxToType = common.IdxToType
	result.IdxToTypeGroup = common.IdxToTypeGroup

	return
}
