// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package query

import "github.com/kazu/fbshelper/query/base"

/*
genny must be called per Field
*/

var (
	Hoges_Files_0 int = base.AtoiNoErr(Atoi("0"))
	Hoges_Files   int = Hoges_Files_0
)

// (field inedx, field type) -> Hoges_IdxToType
var DUMMY_Hoges_Files bool = SetHogesFields("Hoges", "Files", "[]File", Hoges_Files_0)

func (node Hoges) Files() (result *FileList) {
	result = emptyFileList()
	common := node.FieldAt(Hoges_Files_0)
	if common.Node == nil {
		result = NewFileList()
		node.SetFieldAt(Hoges_Files_0, result.SelfAsCommonNode())
		common = node.FieldAt(Hoges_Files_0)
	}

	result.Name = common.Name
	result.NodeList = common.NodeList
	result.IdxToType = common.IdxToType
	result.IdxToTypeGroup = common.IdxToTypeGroup

	return
}

func (node Hoges) SetFiles(v *base.CommonNode) error {

	return node.CommonNode.SetFieldAt(0, v)
}
