// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package query

import "github.com/kazu/fbshelper/query/base"

type HogesList struct { // genny
	*CommonNode
}

// Hoges genny
func NewHogesList() *HogesList {

	list := emptyHogesList()
	list.NodeList = &base.NodeList{}
	list.CommonNode.Name = "[]Hoges"

	(*base.List)(list.CommonNode).InitList()
	return list
}

func emptyHogesList() *HogesList {
	return &HogesList{CommonNode: &base.CommonNode{}}
}

func (node HogesList) At(i int) (result *Hoges, e error) {
	result = &Hoges{}
	result.CommonNode, e = (*base.List)(node.CommonNode).At(i)
	return
}

func (node HogesList) AtWihoutError(i int) (result *Hoges) {
	result, e := node.At(i)
	if e != nil {
		result = nil
	}
	return
}

func (node HogesList) SetAt(i int, v *Hoges) error {
	return (*base.List)(node.CommonNode).SetAt(i, v.CommonNode)
}
func (node HogesList) Add(v HogesList) error {
	return (*base.List)(node.CommonNode).Add((*base.List)(v.CommonNode))
}

func (node HogesList) First() (result *Hoges, e error) {
	return node.At(0)
}

func (node HogesList) Last() (result *Hoges, e error) {
	return node.At(int(node.NodeList.ValueInfo.VLen) - 1)
}

func (node HogesList) Select(fn func(*Hoges) bool) (result []*Hoges) {
	result = make([]*Hoges, 0, int(node.NodeList.ValueInfo.VLen))
	commons := (*base.List)(node.CommonNode).Select(func(cm *CommonNode) bool {
		return fn(&Hoges{CommonNode: cm})
	})
	for _, cm := range commons {
		result = append(result, &Hoges{CommonNode: cm})
	}
	return result
}

func (node HogesList) Find(fn func(*Hoges) bool) *Hoges {
	result := &Hoges{}
	result.CommonNode = (*base.List)(node.CommonNode).Find(func(cm *CommonNode) bool {
		return fn(&Hoges{CommonNode: cm})
	})
	return result
}

func (node HogesList) All() []*Hoges {
	return node.Select(func(*Hoges) bool { return true })
}

func (node HogesList) Count() int {
	return int(node.NodeList.ValueInfo.VLen)
}

func (node HogesList) SwapAt(i, j int) error {
	return (*List)(node.CommonNode).SwapAt(i, j)
}

func (node HogesList) SortBy(less func(i, j int) bool) error {
	return (*List)(node.CommonNode).SortBy(less)
}

// Search ... binary search
func (node HogesList) Search(fn func(*Hoges) bool) *Hoges {
	result := &Hoges{}

	i := (*base.List)(node.CommonNode).SearchIndex(int((*base.List)(node.CommonNode).VLen()), func(cm *CommonNode) bool {
		return fn(&Hoges{CommonNode: cm})
	})
	if i < int((*base.List)(node.CommonNode).VLen()) {
		result, _ = node.At(i)
	}

	return result
}

func (node HogesList) SearchIndex(fn func(*Hoges) bool) int {

	i := (*base.List)(node.CommonNode).SearchIndex(int((*base.List)(node.CommonNode).VLen()), func(cm *CommonNode) bool {
		return fn(&Hoges{CommonNode: cm})
	})
	if i < int((*base.List)(node.CommonNode).VLen()) {
		return i
	}

	return -1
}
