// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package query

import "github.com/kazu/fbshelper/query/base"

/*
must call per Index ;
ILLEGAL genny gen "NodeName=Root Index=Version IndexNum=IndexString,IndexNum" ;
*/

// import (
// 	b "github.com/kazu/fbshelper/query/base"
// )

var DUMMP_IndexIndexNum bool = base.SetAlias("Index", "IndexNum")

func (node Index) IndexNum() IndexNum {
	//result := IndexNum{CommonNode: node.CommonNode}
	result := IndexNum{}
	result.CommonNode = &CommonNode{}
	result.NodeList = node.NodeList
	result.CommonNode.Name = "IndexNum"
	result.FetchIndex()
	return result
}

/*
must call per Index ;
ILLEGAL genny gen "NodeName=Root Index=Version IndexString=IndexString,IndexNum" ;
*/

// import (
// 	b "github.com/kazu/fbshelper/query/base"
// )

var DUMMP_IndexIndexString bool = base.SetAlias("Index", "IndexString")

func (node Index) IndexString() IndexString {
	//result := IndexString{CommonNode: node.CommonNode}
	result := IndexString{}
	result.CommonNode = &CommonNode{}
	result.NodeList = node.NodeList
	result.CommonNode.Name = "IndexString"
	result.FetchIndex()
	return result
}

/*
must call per Index ;
ILLEGAL genny gen "NodeName=Root Index=Version File=IndexString,IndexNum" ;
*/

// import (
// 	b "github.com/kazu/fbshelper/query/base"
// )

var DUMMP_IndexFile bool = base.SetAlias("Index", "File")

func (node Index) File() File {
	//result := File{CommonNode: node.CommonNode}
	result := File{}
	result.CommonNode = &CommonNode{}
	result.NodeList = node.NodeList
	result.CommonNode.Name = "File"
	result.FetchIndex()
	return result
}

/*
must call per Index ;
ILLEGAL genny gen "NodeName=Root Index=Version InvertedMapNum=IndexString,IndexNum" ;
*/

// import (
// 	b "github.com/kazu/fbshelper/query/base"
// )

var DUMMP_IndexInvertedMapNum bool = base.SetAlias("Index", "InvertedMapNum")

func (node Index) InvertedMapNum() InvertedMapNum {
	//result := InvertedMapNum{CommonNode: node.CommonNode}
	result := InvertedMapNum{}
	result.CommonNode = &CommonNode{}
	result.NodeList = node.NodeList
	result.CommonNode.Name = "InvertedMapNum"
	result.FetchIndex()
	return result
}

/*
must call per Index ;
ILLEGAL genny gen "NodeName=Root Index=Version InvertedMapString=IndexString,IndexNum" ;
*/

// import (
// 	b "github.com/kazu/fbshelper/query/base"
// )

var DUMMP_IndexInvertedMapString bool = base.SetAlias("Index", "InvertedMapString")

func (node Index) InvertedMapString() InvertedMapString {
	//result := InvertedMapString{CommonNode: node.CommonNode}
	result := InvertedMapString{}
	result.CommonNode = &CommonNode{}
	result.NodeList = node.NodeList
	result.CommonNode.Name = "InvertedMapString"
	result.FetchIndex()
	return result
}

/*
must call per Index ;
ILLEGAL genny gen "NodeName=Root Index=Version NumList=IndexString,IndexNum" ;
*/

// import (
// 	b "github.com/kazu/fbshelper/query/base"
// )

var DUMMP_IndexNumList bool = base.SetAlias("Index", "NumList")

func (node Index) NumList() NumList {
	//result := NumList{CommonNode: node.CommonNode}
	result := NumList{}
	result.CommonNode = &CommonNode{}
	result.NodeList = node.NodeList
	result.CommonNode.Name = "NumList"
	result.FetchIndex()
	return result
}
