// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package query

import "github.com/kazu/fbshelper/query/base"

/*
    must call 1 times per NodeName
go run github . com / cheekybits / genny gen "Index=Index" ;

*/

// import (
// 	b "github.com/kazu/fbshelper/query/base"
// )

type Index struct {
	*base.CommonNode
}

func NewIndex() *Index {
	result := &Index{CommonNode: &base.CommonNode{}}
	result.Name = "Index"
	return result
}

func (node Index) Member(i int) interface{} {
	return nil
}
