// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package query

import "github.com/kazu/fbshelper/query/base"

// import (
// 	b "github.com/kazu/fbshelper/query/base"
// 	. "github.com/kazu/fbshelper/query/error"
// )

/*
must call 1 times per InvertedMapNum ;
go run github . com / cheekybits / genny gen "InvertedMapNum=Root False=false" ;
*/

type InvertedMapNum struct {
	*base.CommonNode
}

func NewInvertedMapNum() *InvertedMapNum {
	return &InvertedMapNum{CommonNode: &base.CommonNode{}}
}

var InvertedMapNum_IdxToType map[int]int = map[int]int{}
var InvertedMapNum_IdxToTypeGroup map[int]int = map[int]int{}
var InvertedMapNum_IdxToName map[int]string = map[int]string{}
var InvertedMapNum_NameToIdx map[string]int = map[string]int{}

var DUMMP_InvertedMapNumFalse bool = base.SetNameIsStrunct("InvertedMapNum", base.ToBool("False"))

func SetInvertedMapNumFields(nName, fName, fType string, fNum int) bool {
	enumFtype, ok := base.NameToType[fType]
	if ok {
		InvertedMapNumSetIdxToType(fNum, enumFtype)
	}
	//FIXME: 基本型以外は無視?

	InvertedMapNumSetIdxToName(fNum, fType)

	grp := InvertedMapNumGetTypeGroup(fType)
	InvertedMapNumSetTypeGroup(fNum, grp)

	InvertedMapNum_IdxToName[fNum] = fType

	InvertedMapNum_NameToIdx[fName] = fNum
	base.SetNameToIdx("InvertedMapNum", InvertedMapNum_NameToIdx)

	return true

}
func InvertedMapNumSetIdxToName(i int, s string) {
	InvertedMapNum_IdxToName[i] = s

	base.SetIdxToName("InvertedMapNum", InvertedMapNum_IdxToName)
}

func InvertedMapNumSetIdxToType(k, v int) bool {
	InvertedMapNum_IdxToType[k] = v
	base.SetIdxToType("InvertedMapNum", InvertedMapNum_IdxToType)
	return true
}

func InvertedMapNumSetTypeGroup(k, v int) bool {
	InvertedMapNum_IdxToTypeGroup[k] = v
	base.SetdxToTypeGroup("InvertedMapNum", InvertedMapNum_IdxToTypeGroup)
	return true
}

func InvertedMapNumGetTypeGroup(s string) (result int) {
	return base.GetTypeGroup(s)
}

func (node InvertedMapNum) commonNode() *base.CommonNode {
	if node.CommonNode == nil {
		base.Log(base.LOG_WARN, func() base.LogArgs {
			return base.F("CommonNode not found InvertedMapNum")
		})
	} else if len(node.CommonNode.Name) == 0 || len(node.CommonNode.IdxToType) == 0 {
		node.CommonNode.Name = "InvertedMapNum"
		node.CommonNode.IdxToType = InvertedMapNum_IdxToType
		node.CommonNode.IdxToTypeGroup = InvertedMapNum_IdxToTypeGroup
	}
	return node.CommonNode
}
func (node InvertedMapNum) SearchInfo(pos int, fn base.RecFn, condFn base.CondFn) {

	node.commonNode().SearchInfo(pos, fn, condFn)
	// info := node.Info()
	// if condFn(pos, info) {
	// fn(base.NodePath{Name: "InvertedMapNum", Idx: -1}, info)
	// }else{
	//     return
	// }

	// for i := 0; i < node.CountOfField(); i++ {
	// g := InvertedMapNum_IdxToTypeGroup[i]
	//     if node.IsLeafAt(i) {
	//         fInfo := base.Info(node.ValueInfo(i))
	//         if condFn(pos, fInfo) {
	// fn(base.NodePath{Name: "InvertedMapNum", Idx: i}, fInfo)
	//         }
	//         continue
	//     }
	// 	if base.IsMatchBit(g, base.FieldTypeStruct) {
	// 		  node.FieldAt(i).SearchInfo(pos, fn, condFn)
	//     } else if base.IsMatchBit(g, base.FieldTypeUnion) {
	// 		  mNode, _ := node.FieldAt(i).Member(int(node.FieldAt(i - 1).Byte())).(base.Noder)

	// 		  mNode.SearchInfo(pos, fn, condFn)
	// 	} else if base.IsMatchBit(g, base.FieldTypeSlice) && base.IsMatchBit(g, base.FieldTypeBasic1) {
	// 	} else if base.IsMatchBit(g, base.FieldTypeSlice) {
	// 		  node.FieldAt(i).SearchInfo(pos, fn, condFn)
	// 	} else if base.IsMatchBit(g, base.FieldTypeTable) {
	// 		  node.FieldAt(i).SearchInfo(pos, fn, condFn)
	// 	} else if base.IsMatchBit(g, base.FieldTypeBasic) {
	//     } else {
	// 		  base.Log(base.LOG_ERROR, func() base.LogArgs {
	//             return base.F("node must be Noder")
	//         })
	// 	}
	// }
}

// if base.FalseName["InvertedMapNum"] {
// } else if base.IsFieldStruct(i) {
// } else if base.IsFieldUnion(i) {
// } else if base.IsFieldBytes(i) {
// } else if base.IsFieldSlice(i) {
// } else if base.IsFieldTable(i) {
// } else if base.IsFieldBasicType(i) {
// } else {
// 	base.Log(base.LOG_ERROR, func() base.LogArgs {
// return base.F("Invalid %s.%s idx=%d\n", "InvertedMapNum", "FieldName", i)
// 	})
// }

func (node InvertedMapNum) Info() (info base.Info) {

	return node.commonNode().Info()

	// if node.Node == nil {
	// 	node.Node = &base.Node{}
	// }

	// info.Pos = node.Pos
	// info.Size = -1
	// if base.FalseName["InvertedMapNum"] {
	// 	size := 0
	// 	for i :=0; i < node.CountOfField(); i++ {
	// size += base.TypeToSize[InvertedMapNum_IdxToType[i]]
	// 	}
	// 	info.Size = size
	// 	return info
	// }

	// for i := 0; i < len(node.VTable); i++ {
	//     vInfo := node.ValueInfo(i)
	//     if info.Pos + info.Size < vInfo.Pos + vInfo.Size {
	//         info.Size = (vInfo.Pos + vInfo.Size) - info.Pos
	//     }
	// }
	// return info

}

func (node InvertedMapNum) IsLeafAt(j int) bool {

	return node.commonNode().IsLeafAt(j)

	// if base.IsFieldStruct(i) {

	// 	return false
	// } else if base.IsFieldUnion(i) {

	// 	return false
	// } else if base.IsFieldBytes(i) {

	// 	return true
	// } else if base.IsFieldSlice(i) {

	// 	return false
	// } else if base.IsFieldTable(i) {

	// 	return false
	// } else if base.IsFieldBasicType(i) {
	// 	return true
	// } else {
	// 	base.Log(base.LOG_ERROR, func() base.LogArgs {
	// return base.F("Invalid %s.%s idx=%d\n", "InvertedMapNum", "FieldName", i)
	// 	})
	// }
	// return false
}

func (node InvertedMapNum) CountOfField() int {
	return len(InvertedMapNum_IdxToType)
}

func (node InvertedMapNum) ValueInfo(i int) base.ValueInfo {
	return node.commonNode().ValueInfo(i)

	// if base.FalseName["InvertedMapNum"] {
	// 	if len(node.ValueInfos) > i {
	// 		return node.ValueInfos[i]
	// 	}
	// 	node.ValueInfos = make([]base.ValueInfo, 0, node.CountOfField())
	// 	info := base.ValueInfo{Pos: node.Pos, Size: 0}
	// 	for i :=0; i < node.CountOfField(); i++ {
	// 		info.Pos += info.Size
	// info.Size = base.TypeToSize[InvertedMapNum_IdxToType[i]]
	// 		node.ValueInfos = append(node.ValueInfos,  info)
	// 	}
	// }

	// grp := InvertedMapNum_IdxToTypeGroup[i]

	// if base.IsFieldStruct(grp) {
	// 	if node.ValueInfos[i].IsNotReady() {
	// 			node.ValueInfoPos(i)
	// 	}

	// fTypeStr := InvertedMapNum_IdxToName[j]
	// 	idxToType = All_IdxToType[fTypeStr]
	// 	size := 0
	// 	for nextIdx := 0 ; nextIdx < len(idxToType);  nextIdx++ {
	// 		size +=base.TypeToSize[idxToType[nextIdx]]
	// 	}
	// 	node.ValueInfos[i].Size = size

	// } else if base.IsFieldUnion(i) {

	// } else if base.IsFieldBytes(i) {
	// } else if base.IsFieldSlice(i) {
	// } else if base.IsFieldTable(i) {
	// } else if base.IsFieldBasicType(i) {
	// } else {
	// 		base.Log(base.LOG_ERROR, func() base.LogArgs {
	// return base.F("Invalid %s.%s idx=%d\n", "InvertedMapNum", "FieldName", i)
	// 		})
	// }

	// return base.ValueInfo{}
}

func (node InvertedMapNum) FieldAt(idx int) *base.CommonNode {
	//return node.commonNode().FieldAt(idx).NodeList
	return node.commonNode().FieldAt(idx)
}

// func (node InvertedMapNum) SizeAsStruct() int {
// if base.FalseName["InvertedMapNum"] {
// 		size := 0
// 		for i :=0; i < node.CountOfField(); i++ {
// size += base.TypeToSize[InvertedMapNum_IdxToType[i]]
// 		}
// 		return size
// 	}
