// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package query

import "github.com/kazu/fbshelper/query/base"

type NumListList struct { // genny
	*CommonNode
}

// NumList genny
func NewNumListList() *NumListList {

	list := emptyNumListList()
	list.NodeList = &base.NodeList{}
	list.CommonNode.Name = "[]NumList"

	(*base.List)(list.CommonNode).InitList()
	return list
}

func emptyNumListList() *NumListList {
	return &NumListList{CommonNode: &base.CommonNode{}}
}

func (node NumListList) At(i int) (result *NumList, e error) {
	result = &NumList{}
	result.CommonNode, e = (*base.List)(node.CommonNode).At(i)
	return
}

func (node NumListList) SetAt(i int, v *NumList) error {
	return (*base.List)(node.CommonNode).SetAt(i, v.CommonNode)
}

func (node NumListList) First() (result *NumList, e error) {
	return node.At(0)
}

func (node NumListList) Last() (result *NumList, e error) {
	return node.At(int(node.NodeList.ValueInfo.VLen) - 1)
}

func (node NumListList) Select(fn func(*NumList) bool) (result []*NumList) {
	result = make([]*NumList, 0, int(node.NodeList.ValueInfo.VLen))
	commons := (*base.List)(node.CommonNode).Select(func(cm *CommonNode) bool {
		return fn(&NumList{CommonNode: cm})
	})
	for _, cm := range commons {
		result = append(result, &NumList{CommonNode: cm})
	}
	return result
}

func (node NumListList) Find(fn func(*NumList) bool) *NumList {
	result := &NumList{}
	result.CommonNode = (*base.List)(node.CommonNode).Find(func(cm *CommonNode) bool {
		return fn(&NumList{CommonNode: cm})
	})
	return result
}

func (node NumListList) All() []*NumList {
	return node.Select(func(*NumList) bool { return true })
}

func (node NumListList) Count() int {
	return int(node.NodeList.ValueInfo.VLen)
}

func (node NumListList) SwapAt(i, j int) error {
	return (*List)(node.CommonNode).SwapAt(i, j)
}

func (node NumListList) SortBy(less func(i, j int) bool) error {
	return (*List)(node.CommonNode).SortBy(less)
}

// Search ... binary search
func (node NumListList) Search(fn func(*NumList) bool) *NumList {
	result := &NumList{}

	i := (*base.List)(node.CommonNode).SearchIndex(int((*base.List)(node.CommonNode).VLen()), func(cm *CommonNode) bool {
		return fn(&NumList{CommonNode: cm})
	})
	if i < int((*base.List)(node.CommonNode).VLen()) {
		result, _ = node.At(i)
	}

	return result
}
