// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package query

import "github.com/kazu/fbshelper/query/base"

/*
genny must be called per Field
*/

var (
	NumList_Num_0 int = base.AtoiNoErr(Atoi("0"))
	NumList_Num   int = NumList_Num_0
)

// (field inedx, field type) -> NumList_IdxToType
var DUMMY_NumList_Num bool = SetNumListFields("NumList", "Num", "[]int32", NumList_Num_0)

func (node NumList) Num() (result *CommonNode) {
	result = emptyCommonNode()
	common := node.FieldAt(NumList_Num_0)

	result.Name = common.Name
	result.NodeList = common.NodeList
	result.IdxToType = common.IdxToType
	result.IdxToTypeGroup = common.IdxToTypeGroup

	return
}
