// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package query

import "github.com/kazu/fbshelper/query/base"

/*
genny must be called per Field
*/

var (
	Root_IndexType_1 int = base.AtoiNoErr(Atoi("1"))
	Root_IndexType   int = Root_IndexType_1
)

// (field inedx, field type) -> Root_IdxToType
var DUMMY_Root_IndexType bool = SetRootFields("Root", "IndexType", "Byte", Root_IndexType_1)

func (node Root) IndexType() (result *CommonNode) {
	result = NewCommonNode()
	common := node.FieldAt(Root_IndexType_1)

	result.Name = common.Name
	result.NodeList = common.NodeList
	result.IdxToType = common.IdxToType
	result.IdxToTypeGroup = common.IdxToTypeGroup

	return
}
