// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package query

import "github.com/kazu/fbshelper/query/base"

/*
must call per Field
go run github . com / cheekybits / genny gen "Root=Root IndexType=Version Byte=int64 CommonNode=base.CommonNode 1=0 False=false" ;
go run github . com / cheekybits / genny gen "Root=Root IndexType=Index   Byte=Index CommonNode=Index        1=1 False=false" ;
*/

// import (
// 	"github.com/cheekybits/genny/generic"
// 	b "github.com/kazu/fbshelper/query/base"
// )

var (
	Root_IndexType_1 int = base.AtoiNoErr(Atoi("1"))
	Root_IndexType   int = Root_IndexType_1
)

// (field inedx, field type) -> Root_IdxToType
var DUMMY_Root_IndexType bool = SetRootFields("Root", "IndexType", "Byte", Root_IndexType_1)

// RootSetNodeToIdx(Root_IndexType, base.NameToTypeEnum("Byte")) &&
// RootSetIdxToName("Byte", Root_IndexType)

func (node Root) IndexType() (result *CommonNode) {
	result = NewCommonNode()
	common := node.FieldAt(Root_IndexType_1)

	result.Name = common.Name
	result.NodeList = common.NodeList
	result.IdxToType = common.IdxToType
	result.IdxToTypeGroup = common.IdxToTypeGroup

	return
}
