// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package query

import (
	"io"
	"strconv"

	flatbuffers "github.com/google/flatbuffers/go"
	"github.com/kazu/fbshelper/query/base"
)

// go run github.com/cheekybits/genny gen "Root=Root "

// import (
// 	"io"
// 	"strconv"

// 	flatbuffers "github.com/google/flatbuffers/go"
// 	"github.com/kazu/fbshelper/query/base"
// 	b "github.com/kazu/fbshelper/query/base"
// )

//type Root geneic.Type

type CommonNode = base.CommonNode

func NewCommonNode() *base.CommonNode {
	return &base.CommonNode{}
}

func Open(r io.Reader, cap int) Root {
	return Root{CommonNode: base.Open(r, cap)}
}

func OpenByBuf(buf []byte) Root {
	return Root{CommonNode: base.OpenByBuf(buf)}
}

func (node Root) Next() Root {
	start := node.Len()

	if node.LenBuf()+4 < start {
		return node
	}

	newBase := node.Base.NextBase(start)

	root := Root{}
	root.Node = base.NewNode(newBase, int(flatbuffers.GetUOffsetT(newBase.R(0))))
	return root
}

func (node Root) HasNext() bool {

	return node.LenBuf()+4 < node.Len()
}

func Atoi(s string) (int, error) {

	n, err := strconv.Atoi(s)
	if err != nil && s == "FieldNum" {
		err = nil
	}
	return n, err
}
