// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package query

import "github.com/kazu/fbshelper/query/base"

/*
must call 1 times per Table / struct ( Root ) ;
*/

type Root struct {
	*base.CommonNode
}

func NewRoot() *Root {
	return &Root{CommonNode: &base.CommonNode{}}
}

var Root_IdxToType map[int]int = map[int]int{}
var Root_IdxToTypeGroup map[int]int = map[int]int{}
var Root_IdxToName map[int]string = map[int]string{}
var Root_NameToIdx map[string]int = map[string]int{}

var DUMMP_RootFalse bool = base.SetNameIsStrunct("Root", base.ToBool("False"))

func SetRootFields(nName, fName, fType string, fNum int) bool {

	base.RequestSettingNameFields(nName, fName, fType, fNum)

	enumFtype, ok := base.NameToType[fType]
	if ok {
		RootSetIdxToType(fNum, enumFtype)
	}
	//FIXME: basic type only store?

	RootSetIdxToName(fNum, fType)

	grp := RootGetTypeGroup(fType)
	RootSetTypeGroup(fNum, grp)

	Root_IdxToName[fNum] = fType

	Root_NameToIdx[fName] = fNum
	base.SetNameToIdx("Root", Root_NameToIdx)

	return true

}
func RootSetIdxToName(i int, s string) {
	Root_IdxToName[i] = s

	base.SetIdxToName("Root", Root_IdxToName)
}

func RootSetIdxToType(k, v int) bool {
	Root_IdxToType[k] = v
	base.SetIdxToType("Root", Root_IdxToType)
	return true
}

func RootSetTypeGroup(k, v int) bool {
	Root_IdxToTypeGroup[k] = v
	base.SetdxToTypeGroup("Root", Root_IdxToTypeGroup)
	return true
}

func RootGetTypeGroup(s string) (result int) {
	return base.GetTypeGroup(s)
}

func (node Root) commonNode() *base.CommonNode {
	if node.CommonNode == nil {
		base.Log(base.LOG_WARN, func() base.LogArgs {
			return base.F("CommonNode not found Root")
		})
	} else if len(node.CommonNode.Name) == 0 || len(node.CommonNode.IdxToType) == 0 {
		node.CommonNode.Name = "Root"
		node.CommonNode.IdxToType = Root_IdxToType
		node.CommonNode.IdxToTypeGroup = Root_IdxToTypeGroup
	}
	return node.CommonNode
}
func (node Root) SearchInfo(pos int, fn base.RecFn, condFn base.CondFn) {

	node.commonNode().SearchInfo(pos, fn, condFn)

}

func (node Root) Info() (info base.Info) {

	return node.commonNode().Info()

}

func (node Root) IsLeafAt(j int) bool {

	return node.commonNode().IsLeafAt(j)

}

func (node Root) CountOfField() int {
	return len(Root_IdxToType)
}

func (node Root) ValueInfo(i int) base.ValueInfo {
	return node.commonNode().ValueInfo(i)
}

func (node Root) FieldAt(idx int) *base.CommonNode {
	return node.commonNode().FieldAt(idx)
}
