
// Code generated by genmaps.go; DO NOT EDIT.
// template file is https://github.com/kazu/fbshelper/blob/master/template/query.go.tmpl github.com/kazu/fbshelper/template/query.go.tmpl 
//   https://github.com/kazu/fbshelper/blob/master/template/union.query.go.tmpl


package vfs_schema

import (
    flatbuffers "github.com/google/flatbuffers/go"
    base "github.com/kazu/fbshelper/query/base"
    "reflect"
)

const (
    DUMMY_IndexString = flatbuffers.VtableMetadataFields
)

const (
        IndexString_Size =     0
        IndexString_Maps =     1
)

var IndexString_FieldEnum = map[string]int{
        "Size": IndexString_Size,
        "Maps": IndexString_Maps,
}



type FbsIndexString struct {
	*base.Node
}


type FbsIndexStringMaps struct {
    *base.NodeList
}

func (node FbsIndexString) SearchInfo(pos int, fn RecFn, condFn CondFn) {

	info := node.Info()

	if condFn(pos, info) {
		fn(base.NodePath{Name: "IndexString", Idx: -1}, info)
	}else{
        return
    }

	for i := 0; i < node.CountOfField(); i++ {
		if node.IsLeafAt(i) {
			fInfo := base.Info(node.ValueInfo(i))
			if condFn(pos, fInfo) {
				fn(base.NodePath{Name: "IndexString", Idx: i}, fInfo)
			}
			continue
		}
        switch i {
        case 0:
        case 1:
                node.Maps().SearchInfo(pos, fn, condFn)    
        default:
			base.Log(base.LOG_ERROR, func() base.LogArgs {
				return F("node must be Noder")
			})
        }

	}

}
func (node FbsIndexString) Info() base.Info {

    info := base.Info{Pos: node.Pos, Size: -1}
    for i := 0; i < len(node.VTable); i++ {
        vInfo := node.ValueInfo(i)
        if info.Pos + info.Size < vInfo.Pos + vInfo.Size {
            info.Size = (vInfo.Pos + vInfo.Size) - info.Pos
        }
    }
    return info    
}


func (node FbsIndexString) IsLeafAt(i int) bool {
    switch i {
    case 0:
        return true
    case 1:
        return false
    }
    return false
}
func (node FbsIndexString) ValueInfo(i int) base.ValueInfo {

    switch i {
    case 0:
        if node.ValueInfos[i].IsNotReady() {
            node.ValueInfoPos(i)
        }
        node.ValueInfos[i].Size = base.SizeOfint32
    case 1:
         if node.ValueInfos[i].IsNotReady() {
            node.ValueInfoPosList(i)
        }
        node.ValueInfos[i].Size = node.Maps().Info().Size
     }
     return node.ValueInfos[i]
}


func (node FbsIndexString) FieldAt(i int) interface{} {

    switch i {
    case 0:
        return node.Size()
    case 1:
        return node.Maps()
     }
     return nil
}


// Unmarsla parse flatbuffers data and store the result
// in the value point to by v, if v is ni or not pointer,
// Unmarshal returns an ERR_MUST_POINTER, ERR_INVALID_TYPE
func (node FbsIndexString) Unmarshal(v interface{}) error {

    return node.Node.Unmarshal(v, func(s string, rv reflect.Value) error {
        
        switch IndexString_FieldEnum[s] {
        case IndexString_Size:
            //return node.Size()
            rv.Set(reflect.ValueOf(  node.Size() ))
        }
        return nil
    })

}




func (node FbsIndexString) Size() int32 {
    if node.VTable[0] == 0 {
        return int32(0)
    }
    return int32(flatbuffers.GetInt32(node.ValueNormal(0)))
}


func (node FbsIndexString) Maps() FbsIndexStringMaps {
    if node.VTable[1] == 0 {
        return FbsIndexStringMaps{}
    }
    nodelist :=  node.ValueList(1)
    return FbsIndexStringMaps{
                NodeList: &nodelist,
    }
}




func (node FbsIndexString) CountOfField() int {
    return 2
}



        
         
               

func (node FbsIndexStringMaps) At(i int) FbsInvertedMapString {
    if i >= int(node.ValueInfo.VLen) || i < 0 {
        return FbsInvertedMapString{}    
	}

    ptr := int(node.ValueInfo.Pos) + i*4 
	return FbsInvertedMapString{Node: base.NewNode(node.Base, ptr + int(flatbuffers.GetUint32( node.R(ptr) )))}
}


func (node FbsIndexStringMaps) First() FbsInvertedMapString {
	return node.At(0)
}


func (node FbsIndexStringMaps) Last() FbsInvertedMapString {
	return node.At(int(node.ValueInfo.VLen)-1)
}

func (node FbsIndexStringMaps) Select(fn func(m FbsInvertedMapString) bool) []FbsInvertedMapString {

	result := make([]FbsInvertedMapString, 0, int(node.ValueInfo.VLen))
	for i := 0; i < int(node.ValueInfo.VLen); i++ {
		if m := node.At(i); fn(m) {
			result = append(result, m)
		}
	}
	return result
}

func (node FbsIndexStringMaps) Find(fn func(m FbsInvertedMapString) bool) FbsInvertedMapString{

	for i := 0; i < int(node.ValueInfo.VLen); i++ {
		if m := node.At(i); fn(m) {
			return m
		}
	}
    return FbsInvertedMapString{}   

}

func (node FbsIndexStringMaps) All() []FbsInvertedMapString {
	return node.Select(func(m FbsInvertedMapString) bool { return true })
}

func (node FbsIndexStringMaps) Count() int {
	return int(node.ValueInfo.VLen)
}

func (node FbsIndexStringMaps) Info() base.Info {

    info := base.Info{Pos: node.ValueInfo.Pos, Size: -1}
    vInfo := node.Last().Info()



    if info.Pos + info.Size < vInfo.Pos + vInfo.Size {
        info.Size = (vInfo.Pos + vInfo.Size) - info.Pos
    }
    return info
}

func (node FbsIndexStringMaps) SearchInfo(pos int, fn RecFn, condFn CondFn) {

    info := node.Info()

    if condFn(pos, info) {
        fn(base.NodePath{Name: "IndexString.Maps", Idx: -1}, info)
	}else{
        return
    }

    var v interface{}
    for _, cNode := range node.All() {
        v = cNode
        if vv, ok := v.(Searcher); ok {    
                vv.SearchInfo(pos, fn, condFn)
        }else{
            goto NO_NODE
        }
    }
    return
    

NO_NODE:     
    for i := 0 ; i < int(node.ValueInfo.VLen) ; i++ {
        ptr := int(node.ValueInfo.Pos) + i*4
        start := ptr + int(flatbuffers.GetUint32( node.R(ptr) ))
        size := info.Size
        if i + 1 < int(node.ValueInfo.Pos) {
            size = ptr+4 + int(flatbuffers.GetUint32( node.R(ptr+4) )) - start
        }
        cInfo := base.Info{Pos: start, Size: size}
        if condFn(pos, info) {
            fn(base.NodePath{Name: "IndexString.Maps", Idx: i}, cInfo)
        }
    }
}
