
// Code generated by genmaps.go; DO NOT EDIT.
// template file is https://github.com/kazu/fbshelper/blob/master/template/query.go.tmpl github.com/kazu/fbshelper/template/query.go.tmpl 
//   https://github.com/kazu/fbshelper/blob/master/template/union.query.go.tmpl


package vfs_schema

import (
	//flatbuffers "github.com/google/flatbuffers/go"
    base "github.com/kazu/fbshelper/query/base"
)

type EnumIndex byte

const ( 
    IndexNONE                   EnumIndex   =  0
    IndexIndexNum                 EnumIndex   = 1
    IndexIndexString                 EnumIndex   = 2
    IndexFile                 EnumIndex   = 3
    IndexInvertedMapNum                 EnumIndex   = 4
    IndexInvertedMapString                 EnumIndex   = 5
    IndexNumList                 EnumIndex   = 6
)


type FbsIndex struct {
    *base.Node
}
func(node FbsIndex) IndexNum() FbsIndexNum {

    return FbsIndexNum{Node: node.Node}
}
func(node FbsIndex) IndexString() FbsIndexString {

    return FbsIndexString{Node: node.Node}
}
func(node FbsIndex) File() FbsFile {

    return FbsFile{Node: node.Node}
}
func(node FbsIndex) InvertedMapNum() FbsInvertedMapNum {

    return FbsInvertedMapNum{Node: node.Node}
}
func(node FbsIndex) InvertedMapString() FbsInvertedMapString {

    return FbsInvertedMapString{Node: node.Node}
}
func(node FbsIndex) NumList() FbsNumList {

    return FbsNumList{Node: node.Node}
}

func(node FbsIndex) Info(i int) base.Info {
    switch i-1 {
    case 0:
        return node.IndexNum().Info()
    case 1:
        return node.IndexString().Info()
    case 2:
        return node.File().Info()
    case 3:
        return node.InvertedMapNum().Info()
    case 4:
        return node.InvertedMapString().Info()
    case 5:
        return node.NumList().Info()
    }
    return base.Info{}
}

func(node FbsIndex) Member(i int) interface{} {
    switch i-1 {
    case 0:
        return node.IndexNum()
    case 1:
        return node.IndexString()
    case 2:
        return node.File()
    case 3:
        return node.InvertedMapNum()
    case 4:
        return node.InvertedMapString()
    case 5:
        return node.NumList()
    }
    return nil
}


