
// Code generated by genmaps.go; DO NOT EDIT.
// template file is https://github.com/kazu/fbshelper/blob/master/template/query.go.tmpl github.com/kazu/fbshelper/template/query.go.tmpl 
//   https://github.com/kazu/fbshelper/blob/master/template/union.query.go.tmpl


package vfs_schema

import (
    flatbuffers "github.com/google/flatbuffers/go"
    base "github.com/kazu/fbshelper/query/base"
    "reflect"
)

const (
    DUMMY_Symbols = flatbuffers.VtableMetadataFields
)

const (
        Symbols_Symbols =     0
)

var Symbols_FieldEnum = map[string]int{
        "Symbols": Symbols_Symbols,
}



type FbsSymbols struct {
	*base.Node
}


type FbsSymbolsSymbols struct {
    *base.NodeList
}
func (node FbsSymbols) Info() base.Info {

    info := base.Info{Pos: node.Pos, Size: -1}
    for i := 0; i < len(node.VTable); i++ {
        vInfo := node.ValueInfo(i)
        if info.Pos + info.Size < vInfo.Pos + vInfo.Size {
            info.Size = (vInfo.Pos + vInfo.Size) - info.Pos
        }
    }
    return info    
}

func (node FbsSymbols) ValueInfo(i int) base.ValueInfo {

    switch i {
    case 0:
         if node.ValueInfos[i].IsNotReady() {
            node.ValueInfoPosList(i)
        }
        node.ValueInfos[i].Size = node.Symbols().Info().Size
     }
     return node.ValueInfos[i]
}

func (node FbsSymbols) FieldAt(i int) interface{} {

    switch i {
    case 0:
        return node.Symbols()
     }
     return nil
}


// Unmarsla parse flatbuffers data and store the result
// in the value point to by v, if v is ni or not pointer,
// Unmarshal returns an ERR_MUST_POINTER, ERR_INVALID_TYPE
func (node FbsSymbols) Unmarshal(v interface{}) error {

    return node.Node.Unmarshal(v, func(s string, rv reflect.Value) error {
        
        switch Symbols_FieldEnum[s] {
        }
        return nil
    })

}




func (node FbsSymbols) Symbols() FbsSymbolsSymbols {
    if node.VTable[0] == 0 {
        return FbsSymbolsSymbols{}
    }
    nodelist :=  node.ValueList(0)
    return FbsSymbolsSymbols{
                NodeList: &nodelist,
    }
}




func (node FbsSymbols) CountOfField() int {
    return 1
}




func (node FbsSymbolsSymbols) At(i int) FbsSymbol {
    if i > int(node.ValueInfo.VLen) || i < 0 {
		return FbsSymbol{}
	}

	buf := node.Bytes
	ptr := uint32(node.ValueInfo.Pos + (i-1)*4)
	return FbsSymbol{Node: base.NewNode(node.Base, int(ptr+flatbuffers.GetUint32(buf[ptr:])))}
}


func (node FbsSymbolsSymbols) First() FbsSymbol {
	return node.At(0)
}


func (node FbsSymbolsSymbols) Last() FbsSymbol {
	return node.At(int(node.ValueInfo.VLen))
}

func (node FbsSymbolsSymbols) Select(fn func(m FbsSymbol) bool) []FbsSymbol {

	result := make([]FbsSymbol, 0, int(node.ValueInfo.VLen))
	for i := 0; i < int(node.ValueInfo.VLen); i++ {
		if m := node.At(i); fn(m) {
			result = append(result, m)
		}
	}
	return result
}

func (node FbsSymbolsSymbols) Find(fn func(m FbsSymbol) bool) FbsSymbol{

	for i := 0; i < int(node.ValueInfo.VLen); i++ {
		if m := node.At(i); fn(m) {
			return m
		}
	}
	return FbsSymbol{}
}

func (node FbsSymbolsSymbols) All() []FbsSymbol {
	return node.Select(func(m FbsSymbol) bool { return true })
}

func (node FbsSymbolsSymbols) Count() int {
	return int(node.ValueInfo.VLen)
}

func (node FbsSymbolsSymbols) Info() base.Info {

    info := base.Info{Pos: node.ValueInfo.Pos, Size: -1}
    vInfo := node.Last().Info()



    if info.Pos + info.Size < vInfo.Pos + vInfo.Size {
        info.Size = (vInfo.Pos + vInfo.Size) - info.Pos
    }
    return info
}
