
// Code generated by genmaps.go; DO NOT EDIT.
// template file is https://github.com/kazu/fbshelper/blob/master/template/query.go.tmpl github.com/kazu/fbshelper/template/query.go.tmpl 
//   https://github.com/kazu/fbshelper/blob/master/template/union.query.go.tmpl


package vfs_schema

import (
    flatbuffers "github.com/google/flatbuffers/go"
    base "github.com/kazu/fbshelper/query/base"
)

const (
    DUMMY_Symbol = flatbuffers.VtableMetadataFields
)

type FbsSymbol struct {
	*base.Node
}


type FbsSymbolKey struct {
    *base.NodeList
}
func (node FbsSymbol) Info() base.Info {

    info := base.Info{Pos: node.Pos, Size: -1}
    for i := 0; i < len(node.VTable); i++ {
        vInfo := node.ValueInfo(i)
        if info.Pos + info.Size < vInfo.Pos + vInfo.Size {
            info.Size = (vInfo.Pos + vInfo.Size) - info.Pos
        }
    }
    return info    
}

func (node FbsSymbol) ValueInfo(i int) base.ValueInfo {

    switch i {
    case 0:
         if node.ValueInfos[i].IsNotReady() {
            node.ValueInfoPosList(i)
        }
        node.ValueInfos[i].Size = node.Key().Info().Size
     }
     return node.ValueInfos[i]
}





func (node FbsSymbol) Key() FbsSymbolKey {
    if node.VTable[0] == 0 {
        return FbsSymbolKey{}
    }
    nodelist :=  node.ValueList(0)
    return FbsSymbolKey{
                NodeList: &nodelist,
    }
}




type Fbsbytes []byte    
            
            


func (node FbsSymbolKey) At(i int) Fbsbytes {
    if i > int(node.ValueInfo.VLen) || i < 0 {
		return Fbsbytes{}
	}

	buf := node.Bytes
	ptr := uint32(node.ValueInfo.Pos + (i-1)*4)
    return Fbsbytes(base.FbsString(base.NewNode(node.Base, int(ptr+flatbuffers.GetUint32(buf[ptr:])))))
}


func (node FbsSymbolKey) First() Fbsbytes {
	return node.At(0)
}


func (node FbsSymbolKey) Last() Fbsbytes {
	return node.At(int(node.ValueInfo.VLen))
}

func (node FbsSymbolKey) Select(fn func(m Fbsbytes) bool) []Fbsbytes {

	result := make([]Fbsbytes, 0, int(node.ValueInfo.VLen))
	for i := 0; i < int(node.ValueInfo.VLen); i++ {
		if m := node.At(i); fn(m) {
			result = append(result, m)
		}
	}
	return result
}

func (node FbsSymbolKey) Find(fn func(m Fbsbytes) bool) Fbsbytes{

	for i := 0; i < int(node.ValueInfo.VLen); i++ {
		if m := node.At(i); fn(m) {
			return m
		}
	}
	return Fbsbytes{}
}

func (node FbsSymbolKey) All() []Fbsbytes {
	return node.Select(func(m Fbsbytes) bool { return true })
}

func (node FbsSymbolKey) Count() int {
	return int(node.ValueInfo.VLen)
}

func (node FbsSymbolKey) Info() base.Info {

    info := base.Info{Pos: node.ValueInfo.Pos, Size: -1}
    buf := node.Bytes
	ptr := uint32(node.ValueInfo.Pos + (int(node.ValueInfo.VLen)-1)*4)

    vInfo := base.FbsStringInfo(base.NewNode(node.Base, int(ptr+flatbuffers.GetUint32(buf[ptr:]))))



    if info.Pos + info.Size < vInfo.Pos + vInfo.Size {
        info.Size = (vInfo.Pos + vInfo.Size) - info.Pos
    }
    return info
}
